-- =============================================================================
-- Migration 011 — CompanyOwnership (tenant assignment)
-- =============================================================================
-- Assigns a Company record to an owner Company (the app tenant). Many-to-many:
-- a company record can be managed by several owner companies. Self-referential:
-- both columns reference dbo.Company. OwnerCompanyId is the tenant.
-- Ids are generated by the application (Guid v7) — never by SQL defaults.
-- =============================================================================
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.CompanyOwnership', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CompanyOwnership (
        Id             UNIQUEIDENTIFIER NOT NULL,
        OwnerCompanyId UNIQUEIDENTIFIER NOT NULL,
        CompanyId      UNIQUEIDENTIFIER NOT NULL,
        CreatedBy      UNIQUEIDENTIFIER NOT NULL,
        CreatedAt      DATETIME2        NOT NULL,
        UpdatedBy      UNIQUEIDENTIFIER NULL,
        UpdatedAt      DATETIME2        NULL,
        DeletedBy      UNIQUEIDENTIFIER NULL,
        DeletedAt      DATETIME2        NULL,
        IsActive       BIT              NOT NULL CONSTRAINT DF_CompanyOwnership_IsActive DEFAULT (1),
        CONSTRAINT PK_CompanyOwnership PRIMARY KEY CLUSTERED (Id),
        -- NO ACTION on both FKs — self-referential table, avoid cascade cycles.
        CONSTRAINT FK_CompanyOwnership_Owner   FOREIGN KEY (OwnerCompanyId) REFERENCES dbo.Company(Id),
        CONSTRAINT FK_CompanyOwnership_Company FOREIGN KEY (CompanyId)      REFERENCES dbo.Company(Id),
        CONSTRAINT UQ_CompanyOwnership UNIQUE (OwnerCompanyId, CompanyId)
    );

    CREATE INDEX IX_CompanyOwnership_OwnerCompanyId ON dbo.CompanyOwnership (OwnerCompanyId);
    CREATE INDEX IX_CompanyOwnership_CompanyId      ON dbo.CompanyOwnership (CompanyId);

    PRINT '011_company_ownership.sql — dbo.CompanyOwnership created.';
END
ELSE
    PRINT '011_company_ownership.sql — dbo.CompanyOwnership already exists, skipped.';
GO
