-- =============================================================================
-- Migration 012 — CompanyDocument + CompanyDocumentType(+Translation)
-- =============================================================================
-- Company document/image metadata. The file BYTES live in a FileStorage
-- instance (category 'CompanyDocument'), brokered by the FileOrchestrator —
-- this DB stores only metadata. Mirrors KSS.Service.Person's Document stack.
--
--   CompanyDocumentType             — int identity lookup (Code + audit)
--   CompanyDocumentTypeTranslation  — fa/en names (composite PK)
--   CompanyDocument                 — one row per uploaded file (GUID PK)
--
-- Guid ids on CompanyDocument are generated by the application (Guid v7);
-- lookup ids are owned by the database (IDENTITY). Seed language ids are the
-- fixed Common Language ids: fa = 12, en = 10 (matches the frontend + Person).
--
-- Idempotent. Apply to KSS_Company_Prod and KSS_Company_Dev.
-- =============================================================================
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

DECLARE @system UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001';

-- ─────────────────────────────────────────────────────────────────────────
-- 1) CompanyDocumentType (lookup)
-- ─────────────────────────────────────────────────────────────────────────
IF OBJECT_ID(N'dbo.CompanyDocumentType', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CompanyDocumentType (
        Id        INT              IDENTITY(1, 1) NOT NULL,
        Code      VARCHAR(50)      NOT NULL,
        CreatedBy UNIQUEIDENTIFIER NOT NULL,
        CreatedAt DATETIME2        NOT NULL,
        UpdatedBy UNIQUEIDENTIFIER NULL,
        UpdatedAt DATETIME2        NULL,
        DeletedBy UNIQUEIDENTIFIER NULL,
        DeletedAt DATETIME2        NULL,
        IsActive  BIT              NOT NULL CONSTRAINT DF_CompanyDocumentType_IsActive DEFAULT (1),
        CONSTRAINT PK_CompanyDocumentType PRIMARY KEY CLUSTERED (Id),
        CONSTRAINT UQ_CompanyDocumentType_Code UNIQUE (Code)
    );
    PRINT '012 — dbo.CompanyDocumentType created.';
END
ELSE
    PRINT '012 — dbo.CompanyDocumentType already exists, skipped.';
GO

-- ─────────────────────────────────────────────────────────────────────────
-- 2) CompanyDocumentTypeTranslation (fa/en names)
-- ─────────────────────────────────────────────────────────────────────────
IF OBJECT_ID(N'dbo.CompanyDocumentTypeTranslation', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CompanyDocumentTypeTranslation (
        CompanyDocumentTypeId INT              NOT NULL,
        LanguageId            SMALLINT         NOT NULL,
        Name                  NVARCHAR(50)     NOT NULL,
        CreatedBy             UNIQUEIDENTIFIER NOT NULL,
        CreatedAt             DATETIME2        NOT NULL,
        UpdatedBy             UNIQUEIDENTIFIER NULL,
        UpdatedAt             DATETIME2        NULL,
        DeletedBy             UNIQUEIDENTIFIER NULL,
        DeletedAt             DATETIME2        NULL,
        CONSTRAINT PK_CompanyDocumentTypeTranslation PRIMARY KEY CLUSTERED (CompanyDocumentTypeId, LanguageId),
        CONSTRAINT FK_CompanyDocumentTypeTranslation_Type
            FOREIGN KEY (CompanyDocumentTypeId) REFERENCES dbo.CompanyDocumentType (Id) ON DELETE CASCADE
    );
    CREATE NONCLUSTERED INDEX IX_CompanyDocumentTypeTranslation_LanguageId
        ON dbo.CompanyDocumentTypeTranslation (LanguageId);
    PRINT '012 — dbo.CompanyDocumentTypeTranslation created.';
END
ELSE
    PRINT '012 — dbo.CompanyDocumentTypeTranslation already exists, skipped.';
GO

-- ─────────────────────────────────────────────────────────────────────────
-- 3) CompanyDocument (metadata; bytes live in FileStorage)
-- ─────────────────────────────────────────────────────────────────────────
IF OBJECT_ID(N'dbo.CompanyDocument', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CompanyDocument (
        Id                    UNIQUEIDENTIFIER NOT NULL,
        CompanyId             UNIQUEIDENTIFIER NOT NULL,
        CompanyDocumentTypeId INT              NOT NULL,
        StorageInstanceId     INT              NOT NULL,
        FileName              NVARCHAR(255)    NOT NULL,
        FileSize              BIGINT           NOT NULL,
        ContentType           VARCHAR(100)     NOT NULL,
        CreatedBy             UNIQUEIDENTIFIER NOT NULL,
        CreatedAt             DATETIME2        NOT NULL,
        UpdatedBy             UNIQUEIDENTIFIER NULL,
        UpdatedAt             DATETIME2        NULL,
        DeletedBy             UNIQUEIDENTIFIER NULL,
        DeletedAt             DATETIME2        NULL,
        IsActive              BIT              NOT NULL CONSTRAINT DF_CompanyDocument_IsActive DEFAULT (1),
        CONSTRAINT PK_CompanyDocument PRIMARY KEY CLUSTERED (Id),
        CONSTRAINT FK_CompanyDocument_Company
            FOREIGN KEY (CompanyId) REFERENCES dbo.Company (Id) ON DELETE CASCADE,
        CONSTRAINT FK_CompanyDocument_Type
            FOREIGN KEY (CompanyDocumentTypeId) REFERENCES dbo.CompanyDocumentType (Id)
    );
    CREATE NONCLUSTERED INDEX IX_CompanyDocument_CompanyId ON dbo.CompanyDocument (CompanyId);
    PRINT '012 — dbo.CompanyDocument created.';
END
ELSE
    PRINT '012 — dbo.CompanyDocument already exists, skipped.';
GO

-- ─────────────────────────────────────────────────────────────────────────
-- 4) Seed CompanyDocumentType (+ fa/en translations). Guarded — runs once.
--    Order matches the agreed 10-row list (formation/legal → identity/tax →
--    financial/org → media).
-- ─────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM dbo.CompanyDocumentType)
BEGIN
    DECLARE @sys UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001';
    DECLARE @now DATETIME2 = SYSUTCDATETIME();

    INSERT INTO dbo.CompanyDocumentType (Code, CreatedBy, CreatedAt) VALUES
        ('RN',   @sys, @now),
        ('AOA',  @sys, @now),
        ('OG',   @sys, @now),
        ('LCG',  @sys, @now),
        ('PG',   @sys, @now),
        ('NID',  @sys, @now),
        ('ECC',  @sys, @now),
        ('FS',   @sys, @now),
        ('OC',   @sys, @now),
        ('LOGO', @sys, @now);

    ;WITH v AS (
        SELECT Code, LanguageId, Name FROM (VALUES
            ('RN',   10, N'Registration Notice'),            ('RN',   12, N'آگهی تأسیس'),
            ('AOA',  10, N'Articles of Association'),         ('AOA',  12, N'اساسنامه'),
            ('OG',   10, N'Official Gazette'),                ('OG',   12, N'روزنامه رسمی'),
            ('LCG',  10, N'Latest Changes Gazette'),          ('LCG',  12, N'روزنامه رسمی آخرین تغییرات'),
            ('PG',   10, N'Public Gazette'),                  ('PG',   12, N'روزنامه عمومی'),
            ('NID',  10, N'National ID Certificate'),         ('NID',  12, N'گواهی شناسه ملی'),
            ('ECC',  10, N'Economic Code Certificate'),       ('ECC',  12, N'گواهی کد اقتصادی'),
            ('FS',   10, N'Financial Statements'),            ('FS',   12, N'صورت‌های مالی'),
            ('OC',   10, N'Organizational Chart'),            ('OC',   12, N'چارت سازمانی'),
            ('LOGO', 10, N'Company Logo / Picture'),          ('LOGO', 12, N'لوگو / تصویر شرکت')
        ) AS x(Code, LanguageId, Name)
    )
    INSERT INTO dbo.CompanyDocumentTypeTranslation (CompanyDocumentTypeId, LanguageId, Name, CreatedBy, CreatedAt)
    SELECT t.Id, v.LanguageId, v.Name, @sys, @now
    FROM v
    JOIN dbo.CompanyDocumentType t ON t.Code = v.Code;

    PRINT '012 — CompanyDocumentType seeded (10 types, fa/en).';
END
ELSE
    PRINT '012 — CompanyDocumentType already seeded, skipped.';
GO
