using System.Security.Claims;
using AutoMapper;
using KSS.Dto;
using KSS.Entity;
using KSS.Helper;
using KSS.Repository.IRepository;
using KSS.Service.IService;
using Microsoft.AspNetCore.Http;

namespace KSS.Service.Service
{
    /// <summary>
    /// Adds the name translations of a company being created in the same operation.
    /// Internal to this assembly, so no controller can reach it.
    /// </summary>
    internal interface INewCompanyNameHistoryTranslation
    {
        Task AddForNewCompanyAsync(NameHistoryTranslationDto item);
    }

    /// <summary>
    /// Single-table CRUD service for NameHistoryTranslation.
    /// Multi-table orchestration (sync to Translation, etc.) is handled by CompanyNameManagementService.
    /// </summary>
    public class NameHistoryTranslationService : BaseService<NameHistoryTranslation, NameHistoryTranslationDto, NameHistoryTranslationDto, NameHistoryTranslationDto>, INameHistoryTranslationService, INewCompanyNameHistoryTranslation, ICompanyScopedWrites
    {
        private const int ModifyLevel = 2;
        private const string ModifyDenied = "You do not have permission to modify this company's name history translations.";
        private const string NameHistoryNotFound = "Name history entry not found.";

        private readonly INameHistoryTranslationRepository _translationRepository;
        private readonly INameHistoryRepository _nameHistoryRepository;
        private readonly IAccessService _accessService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public NameHistoryTranslationService(
            IMapper mapper,
            INameHistoryTranslationRepository repository,
            INameHistoryRepository nameHistoryRepository,
            IAccessService accessService,
            IHttpContextAccessor httpContextAccessor) : base(mapper, repository)
        {
            _translationRepository = repository;
            _nameHistoryRepository = nameHistoryRepository;
            _accessService = accessService;
            _httpContextAccessor = httpContextAccessor;
        }

        // Every write reachable through BaseController checks Information level 2 on the
        // company of the stored name history entry the translation belongs to. The entry is
        // part of this row's key, so a row cannot change entry; updates and removals load
        // the stored row by its key. Range operations check every item before anything is
        // written.

        public override async Task AddAsync(NameHistoryTranslation item, bool saveChanges = true)
        {
            await RequireModifyOnEveryEntryAsync(new[] { item.NameHistoryId });
            await base.AddAsync(item, saveChanges);
        }

        public override async Task AddDtoAsync(NameHistoryTranslationDto item, bool saveChanges = true)
        {
            await RequireModifyOnEveryEntryAsync(new[] { item.NameHistoryId });
            await base.AddDtoAsync(item, saveChanges);
        }

        public override async Task AddRangeAsync(IEnumerable<NameHistoryTranslation> items, bool saveChanges = true)
        {
            var list = items.ToList();
            await RequireModifyOnEveryEntryAsync(list.Select(x => x.NameHistoryId));
            await base.AddRangeAsync(list, saveChanges);
        }

        // Company creation adds the name translations of a company whose id is generated by
        // the server in the same operation, so there is no existing company to protect.
        Task INewCompanyNameHistoryTranslation.AddForNewCompanyAsync(NameHistoryTranslationDto item) => base.AddDtoAsync(item, true);

        public override void Update(NameHistoryTranslation item, bool saveChanges = true)
        {
            var stored = PrepareUpdates(new[] { item });
            base.Update(stored[0], saveChanges);
        }

        public override void UpdateRange(IEnumerable<NameHistoryTranslation> items, bool saveChanges = true)
        {
            base.UpdateRange(PrepareUpdates(items), saveChanges);
        }

        /// <summary>
        /// Load existing entity first, then only update the editable fields.
        /// Prevents DbUpdateConcurrencyException from _dbSet.Update() on detached entity.
        /// </summary>
        public override void UpdateDto(NameHistoryTranslationDto item, bool saveChanges = true)
        {
            var existing = _translationRepository.SingleOrDefault(
                t => t.NameHistoryId == item.NameHistoryId && t.LanguageId == item.LanguageId)
                ?? throw new KeyNotFoundException(
                    $"NameHistoryTranslation with key ({item.NameHistoryId}, {item.LanguageId}) not found.");

            RequireModifyOnEveryEntryAsync(new[] { existing.NameHistoryId }).GetAwaiter().GetResult();

            existing.Name = item.Name;
            existing.ShortName = item.ShortName;

            base.Update(existing, saveChanges);
        }

        public override void Remove(NameHistoryTranslation item, bool saveChanges = true)
        {
            var stored = FindStored(item);
            if (stored == null)
                return;

            RequireModifyOnEveryEntryAsync(new[] { stored.NameHistoryId }).GetAwaiter().GetResult();
            // The tracked stored row is removed, not the request instance.
            base.Remove(stored, saveChanges);
        }

        public override void RemoveRange(IEnumerable<NameHistoryTranslation> items, bool saveChanges = true)
        {
            var stored = items.Select(FindStored).Where(x => x != null).Select(x => x!).ToList();

            RequireModifyOnEveryEntryAsync(stored.Select(x => x.NameHistoryId)).GetAwaiter().GetResult();
            base.RemoveRange(stored, saveChanges);
        }

        private NameHistoryTranslation? FindStored(NameHistoryTranslation item) =>
            _translationRepository.SingleOrDefault(t => t.NameHistoryId == item.NameHistoryId && t.LanguageId == item.LanguageId);

        // Loads every stored row by its key and checks all of them before any value is
        // applied, then copies the request's values onto the tracked stored rows.
        private List<NameHistoryTranslation> PrepareUpdates(IEnumerable<NameHistoryTranslation> items)
        {
            var pairs = items
                .Select(item => (Item: item, Stored: FindStored(item)
                    ?? throw new KeyNotFoundException($"NameHistoryTranslation with key ({item.NameHistoryId}, {item.LanguageId}) not found.")))
                .ToList();

            RequireModifyOnEveryEntryAsync(pairs.Select(p => p.Stored.NameHistoryId)).GetAwaiter().GetResult();

            foreach (var (item, stored) in pairs)
                CopyScalarValues(item, stored);

            return pairs.Select(p => p.Stored).ToList();
        }

        // Scalar columns only; navigation properties and the key are left untouched.
        private static void CopyScalarValues(NameHistoryTranslation source, NameHistoryTranslation target)
        {
            foreach (var property in typeof(NameHistoryTranslation).GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance))
            {
                if (!property.CanRead || !property.CanWrite
                    || property.Name == nameof(NameHistoryTranslation.NameHistoryId) || property.Name == nameof(NameHistoryTranslation.LanguageId))
                    continue;

                var type = property.PropertyType;
                if (type.IsValueType || type == typeof(string))
                    property.SetValue(target, property.GetValue(source));
            }
        }

        // Resolves each name history entry to its stored company and checks every company.
        // An entry that does not exist has no company to check against and is refused.
        private async Task RequireModifyOnEveryEntryAsync(IEnumerable<Guid> nameHistoryIds)
        {
            var companyIds = new List<Guid>();
            foreach (var nameHistoryId in nameHistoryIds.Distinct())
            {
                var entry = _nameHistoryRepository.SingleOrDefault(h => h.Id == nameHistoryId)
                    ?? throw new BusinessRuleException(NameHistoryNotFound);
                companyIds.Add(entry.CompanyId);
            }

            foreach (var companyId in companyIds.Distinct())
                await RequireNameHistoryTranslationModifyAsync(companyId);
        }

        // The Information.Modify permission (checked by the permission filter) is global to
        // the caller. This confirms the caller also holds Information level 2 on the
        // specific company the rows belong to. Fails closed: no caller, or a lower level,
        // is denied.
        private async Task RequireNameHistoryTranslationModifyAsync(Guid companyId)
        {
            var levels = await _accessService.GetLevelsAsync(companyId, GetCallerPersonId());
            if (levels.Information < ModifyLevel)
                throw new BusinessRuleException(ModifyDenied);
        }

        private Guid GetCallerPersonId()
        {
            var user = _httpContextAccessor.HttpContext?.User;
            var raw = user?.FindFirstValue("personId")
                   ?? user?.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(raw) || !Guid.TryParse(raw, out var personId))
                throw new BusinessRuleException("Caller PersonId not found on the JWT.");
            return personId;
        }
    }
}
