using System.Security.Claims;
using AutoMapper;
using KSS.Dto;
using KSS.Entity;
using KSS.Helper;
using KSS.Repository.IRepository;
using KSS.Service.IService;
using Microsoft.AspNetCore.Http;

namespace KSS.Service.Service
{
    /// <summary>
    /// Adds the names of a company being created in the same operation.
    /// Internal to this assembly, so no controller can reach it.
    /// </summary>
    internal interface INewCompanyTranslation
    {
        Task AddForNewCompanyAsync(TranslationDto item);
    }

    public class TranslationService : BaseService<Translation, TranslationDto, TranslationDto, TranslationDto>, ITranslationService, INewCompanyTranslation, ICompanyScopedWrites
    {
        private const int ModifyLevel = 2;
        private const string ModifyDenied = "You do not have permission to modify this company's name translations.";

        private readonly ITranslationRepository _translationRepository;
        private readonly IAccessService _accessService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public TranslationService(
            IMapper mapper,
            ITranslationRepository repository,
            IAccessService accessService,
            IHttpContextAccessor httpContextAccessor) : base(mapper, repository)
        {
            _translationRepository = repository;
            _accessService = accessService;
            _httpContextAccessor = httpContextAccessor;
        }

        // Every write reachable through BaseController checks Information level 2 on the
        // company the row belongs to. The company is part of this row's key, so a row
        // cannot change company; updates and removals load the stored row by its key.
        // Range operations check every item before anything is written.

        public override async Task AddAsync(Translation item, bool saveChanges = true)
        {
            await RequireTranslationModifyAsync(item.CompanyId);
            await base.AddAsync(item, saveChanges);
        }

        public override async Task AddDtoAsync(TranslationDto item, bool saveChanges = true)
        {
            await RequireTranslationModifyAsync(item.CompanyId);
            await base.AddDtoAsync(item, saveChanges);
        }

        public override async Task AddRangeAsync(IEnumerable<Translation> items, bool saveChanges = true)
        {
            var list = items.ToList();
            await RequireModifyOnEveryCompanyAsync(list.Select(x => x.CompanyId));
            await base.AddRangeAsync(list, saveChanges);
        }

        // Company creation adds the names of a company whose id is generated by the server
        // in the same operation, so there is no existing company to protect.
        Task INewCompanyTranslation.AddForNewCompanyAsync(TranslationDto item) => base.AddDtoAsync(item, true);

        public override void Update(Translation item, bool saveChanges = true)
        {
            var stored = PrepareUpdates(new[] { item });
            base.Update(stored[0], saveChanges);
        }

        public override void UpdateRange(IEnumerable<Translation> items, bool saveChanges = true)
        {
            base.UpdateRange(PrepareUpdates(items), saveChanges);
        }

        /// <summary>
        /// Load existing entity first, then only update the editable fields.
        /// Prevents DbUpdateConcurrencyException from _dbSet.Update() on detached entity
        /// and avoids overwriting ShortName/Description with null when not provided.
        /// </summary>
        public override void UpdateDto(TranslationDto item, bool saveChanges = true)
        {
            var existing = _translationRepository.SingleOrDefault(
                t => t.CompanyId == item.CompanyId && t.LanguageId == item.LanguageId)
                ?? throw new KeyNotFoundException(
                    $"Translation with key ({item.CompanyId}, {item.LanguageId}) not found.");

            RequireTranslationModifyAsync(existing.CompanyId).GetAwaiter().GetResult();

            existing.Name = item.Name;
            existing.ShortName = item.ShortName;
            existing.Description = item.Description;

            base.Update(existing, saveChanges);
        }

        public override void Remove(Translation item, bool saveChanges = true)
        {
            var stored = FindStored(item);
            if (stored == null)
                return;

            RequireTranslationModifyAsync(stored.CompanyId).GetAwaiter().GetResult();
            // The tracked stored row is removed, not the request instance.
            base.Remove(stored, saveChanges);
        }

        public override void RemoveRange(IEnumerable<Translation> items, bool saveChanges = true)
        {
            var stored = items.Select(FindStored).Where(x => x != null).Select(x => x!).ToList();

            RequireModifyOnEveryCompanyAsync(stored.Select(x => x.CompanyId)).GetAwaiter().GetResult();
            base.RemoveRange(stored, saveChanges);
        }

        private Translation? FindStored(Translation item) =>
            _translationRepository.SingleOrDefault(t => t.CompanyId == item.CompanyId && t.LanguageId == item.LanguageId);

        // Loads every stored row by its key and checks all of them before any value is
        // applied, then copies the request's values onto the tracked stored rows.
        private List<Translation> PrepareUpdates(IEnumerable<Translation> items)
        {
            var pairs = items
                .Select(item => (Item: item, Stored: FindStored(item)
                    ?? throw new KeyNotFoundException($"Translation with key ({item.CompanyId}, {item.LanguageId}) not found.")))
                .ToList();

            RequireModifyOnEveryCompanyAsync(pairs.Select(p => p.Stored.CompanyId)).GetAwaiter().GetResult();

            foreach (var (item, stored) in pairs)
                CopyScalarValues(item, stored);

            return pairs.Select(p => p.Stored).ToList();
        }

        // Scalar columns only; navigation properties and the key are left untouched.
        private static void CopyScalarValues(Translation source, Translation target)
        {
            foreach (var property in typeof(Translation).GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance))
            {
                if (!property.CanRead || !property.CanWrite
                    || property.Name == nameof(Translation.CompanyId) || property.Name == nameof(Translation.LanguageId))
                    continue;

                var type = property.PropertyType;
                if (type.IsValueType || type == typeof(string))
                    property.SetValue(target, property.GetValue(source));
            }
        }

        private async Task RequireModifyOnEveryCompanyAsync(IEnumerable<Guid> companyIds)
        {
            foreach (var companyId in companyIds.Distinct())
                await RequireTranslationModifyAsync(companyId);
        }

        // The Information.Modify permission (checked by the permission filter) is global to
        // the caller. This confirms the caller also holds Information level 2 on the
        // specific company the rows belong to. Fails closed: no caller, or a lower level,
        // is denied.
        private async Task RequireTranslationModifyAsync(Guid companyId)
        {
            var levels = await _accessService.GetLevelsAsync(companyId, GetCallerPersonId());
            if (levels.Information < ModifyLevel)
                throw new BusinessRuleException(ModifyDenied);
        }

        private Guid GetCallerPersonId()
        {
            var user = _httpContextAccessor.HttpContext?.User;
            var raw = user?.FindFirstValue("personId")
                   ?? user?.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(raw) || !Guid.TryParse(raw, out var personId))
                throw new BusinessRuleException("Caller PersonId not found on the JWT.");
            return personId;
        }
    }
}
